name: CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Test
      run: |
        cd build
        ctest --output-on-failure || true

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: house_and_theme_tests
        path: build
